/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.itoaxaca.gui;

import edu.itoaxaca.ficheros.manejador.archivos.ManejadorArchivos;
import edu.itoaxaca.ia.red.RedNeuronal;
import edu.itoaxaca.manejador.obj.ManejadorObjetos;
import edu.itoaxaca.utilities.ConversorStrBin;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laibr
 */
public class InterfazPrincipal extends javax.swing.JFrame {
    private int fila;
    private RedNeuronal cifrado,descifrado;
    private double[] inputs,outputs;
    List<String[]> datos;
    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal(){
        initComponents();
        try{
        datos = ManejadorArchivos.leerDatos("D:\\datos.csv");
        Object[][] filas = new Object[datos.size()][4];
        int cont = 0;
        for(String[] array:datos){filas[cont++] = array;}
        String[] columnas = {"Normal","Normal (bin)","Cifrado","Cifrado (bin)"};
        DefaultTableModel modelo = new DefaultTableModel(filas,columnas);
        tabla.setModel(modelo);
        fila = -1;
        lb_row_selected.setText(Integer.toString(fila));
        btn_probar.setEnabled(false);
        File ficheroEncrypt = new File("D:\\IA\\encriptado\\2\\RED_ENCRYPT_500X700-0.08.obj");
        File ficheroDecrypt = new File("D:\\IA\\desencriptado\\1\\RED_DECRYPT.obj");
        cifrado = (RedNeuronal) ManejadorObjetos.readObj(ficheroEncrypt);
        descifrado = (RedNeuronal) ManejadorObjetos.readObj(ficheroDecrypt);
        //System.out.println(ConversorStrBin.toString("110001011011110110111001101011011100000011000000111001001101000011010001110001001101010011011101100111011011100011100101110111011010110110011001101110001101000111000100110100011011100111000100110111011101110110100101100101011011010011010001110101001100100011100001110100011101010011010101110101011101110110110101101000011110100011001001111001011011010110011100111001011000110111010001110110001110000011000100110011011101010110101101100010011110100110000101110010011110010110010101100001011110100110000101110100001100010111000100111001011011010011011000111001011001000110000101110101011100000011011100110000001100000011000101100010011100000111001101100011011010110110011101100001011010000011000100110010001100100111001001110100011100100110000101100100011101010011000000110101011011110111001001110001"));
        }catch(Exception e){e.printStackTrace();}
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lb_row_selected = new javax.swing.JLabel();
        btn_probar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        encrypt = new javax.swing.JCheckBox();
        decrypt = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextPane();
        btn_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sets de datos");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Normal", "Normal (bin)", "Encriptado", "Encriptado (bin)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel2.setText("Fila seleccionada:");

        lb_row_selected.setText("jLabel3");

        btn_probar.setText("Probar");
        btn_probar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_probarActionPerformed(evt);
            }
        });

        jLabel3.setText("Output");

        jLabel4.setText("Red a usar:");

        encrypt.setText("Encriptador");

        decrypt.setText("Desencriptador");

        jScrollPane2.setViewportView(salida);

        jScrollPane3.setViewportView(jScrollPane2);

        btn_clear.setText("Limpiar");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(408, 408, 408))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lb_row_selected)
                            .addGap(51, 51, 51)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(encrypt)
                            .addGap(18, 18, 18)
                            .addComponent(decrypt)
                            .addGap(288, 288, 288)
                            .addComponent(btn_probar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_clear)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lb_row_selected)
                            .addComponent(jLabel4)
                            .addComponent(encrypt)
                            .addComponent(decrypt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(btn_probar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btn_clear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        fila = tabla.getSelectedRow();
        lb_row_selected.setText(Integer.toString(fila+1));
        btn_probar.setEnabled(true);
    }//GEN-LAST:event_tablaMouseClicked

    private void tablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMousePressed
        fila = tabla.getSelectedRow();
        lb_row_selected.setText(Integer.toString(fila+1));
        btn_probar.setEnabled(true);
    }//GEN-LAST:event_tablaMousePressed

    private void btn_probarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_probarActionPerformed
        asignarEntradas(fila);
    }//GEN-LAST:event_btn_probarActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
       salida.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed
    
    public void asignarEntradas(int row){
        if(encrypt.isSelected()){
        inputs = ConversorStrBin.toDouble(datos.get(row)[1]);
        double[] output = cifrado.getOutputs();
        String bin = "";
        for(double d:output){bin += Integer.toString((int)(Math.abs(d)));}
        if(inputs.length == 415){cifrado.feed_forward(inputs); 
        salida.setText(salida.getText() + "Salida cifrada: " + ConversorStrBin.toString(bin)/*this.printArray(cifrado.getOutputs())*/ + "\n");}
        }
        
        if(decrypt.isSelected()){
        inputs = ConversorStrBin.toDouble(datos.get(row)[3]);
        double[] output = descifrado.getOutputs();
        String bin = "";
        for(double d:output){bin += Integer.toString(Math.abs((int)d));}
        if(inputs.length == 798){descifrado.feed_forward(inputs); 
        salida.setText(salida.getText() + "Salida descifrada: " + ConversorStrBin.toString(bin)/*this.printArray(descifrado.getOutputs())*/ + "\n");}
        }
    }
    
    public String printArray(double[] o) {
        String s = "[";
        int cont = 0;
        for (double d : o) {
            if (cont == o.length - 1) {
                s += d + "]";
            } else {
                s += d + ",";
            }
            cont++;
        }
        return s;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_probar;
    private javax.swing.JCheckBox decrypt;
    private javax.swing.JCheckBox encrypt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_row_selected;
    private javax.swing.JTextPane salida;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
